// Independent template draft; navigation never implicitly applies it to a PDA.
let templateRowsFlow=JSON.parse(JSON.stringify(rows));
let reviewOriginFlow='detail';
try{const saved=JSON.parse(localStorage.getItem('pda-template-draft')||'null');if(saved){templateRowsFlow=saved.rows;templateDraftUI.name=saved.name;templateDraftUI.scope=saved.scope;}}catch{}
function saveTemplateDraftFlow(){localStorage.setItem('pda-template-draft',JSON.stringify({rows:templateRowsFlow,name:templateDraftUI.name,scope:templateDraftUI.scope}));}
const oldTemplatesFlow=templates;
templates=function(){if(mode==='actual')return templateReferenceFlow();const current=rows;try{rows=templateRowsFlow;return oldTemplatesFlow();}finally{rows=current;}};
const oldRenderFlow=render;
render=function(){oldRenderFlow();if(page==='templates'&&mode==='actual'){document.querySelector('[data-action="menu"]').textContent='▱ PDA Plantilla ⌄';return;}if(mode!=='proposed')return;
 const menu=document.querySelector('[data-action="menu"]');if(menu)menu.textContent=page==='templates'?'▱ PDA Plantilla ⌄':'▱ PDA ⌄';
 if(page==='templates'){
  const crumbNode=document.querySelector('.crumb');if(crumbNode)crumbNode.innerHTML='Inicio <span>/</span> PDA Plantilla <span>/</span> Editar plantilla';
  const reviewButton=document.querySelector('[data-action="template-review-services"]');if(reviewButton)reviewButton.textContent='Revisar tarifas de la plantilla';
  const input=document.querySelector('#tpl-name');if(input&&templateDraftUI.name!==null)input.value=templateDraftUI.name;
  const scope=document.querySelector('#tpl-scope');if(scope){scope.required=true;scope.value=templateDraftUI.scope||'Callao · DP World · Liner';}
  document.querySelector('.template-main .footerbar small').textContent='Esta versión no modifica los servicios de la PDA.';
 }
};
if(templateDraftUI.name==='')templateDraftUI.name=pda.port+' · '+pda.service;
const requiredFlow={vessel:'Nave o referencia TBN',client:'Cliente solicitante',billTo:'Cliente facturador',voyage:'Viaje / referencia',service:'Tipo de servicio',agency:'Agenciamiento',operation:'Operación',cargo:'Tipo de carga',port:'Puerto',terminal:'Terminal',eta:'ETA',etd:'ETD',currency:'Moneda'};
function fieldIssuesFlow(){const issues=[];for(const [key,label]of Object.entries(requiredFlow)){const value=String(pda[key]??'').trim();if(!value||value==='Por definir')issues.push({key,message:label+': completa este campo para aprobar.'});}
 if(!Number.isFinite(Number(pda.exchange))||Number(pda.exchange)<=0)issues.push({key:'exchange',message:'Tipo de cambio: ingresa un número mayor que cero.'});
 for(const [key,unit,label]of [['grt','TRG × cantidad','TRG / GRT'],['loa','LOA × horas','Eslora / LOA']])if(rows.some(r=>r.enabled&&r.unit===unit)&&(!Number.isFinite(Number(pda[key]))||Number(pda[key])<=0))issues.push({key,message:label+': necesario para los servicios seleccionados.'});
 for(const key of ['eta','etd'])if(pda[key]&&Number.isNaN(Date.parse(pda[key])))issues.push({key,message:key.toUpperCase()+': fecha no válida.'});
 if(Date.parse(pda.etd)<Date.parse(pda.eta))issues.push({key:'etd',message:'ETD debe ser igual o posterior a ETA.'});return issues;}
const oldApprovalFlow=approvalIssues;
approvalIssues=function(){return [...new Set([...fieldIssuesFlow().map(x=>x.message),...oldApprovalFlow(),...rows.filter(r=>r.enabled).flatMap(r=>{const out=[];if(!String(r.es||'').trim()||!String(r.en||'').trim())out.push('Completa los nombres ES y EN de cada servicio.');if(!String(r.rate??'').trim()||!Number.isFinite(Number(r.rate))||Number(r.rate)<0)out.push(r.es+': tarifa no válida.');if(!String(r.qty??'').trim()||!Number.isFinite(Number(r.qty))||Number(r.qty)<0)out.push(r.es+': cantidad no válida.');if(!['included','excluded','exempt','unaffected'].includes(r.tax))out.push(r.es+': clasifica el IGV.');return out;})])];};
changed=function(text){pda.confirmed=false;pda.sent=false;pda.associated=false;pda.status='Creado';pda.stage='Creado';pda.surchargesRecalculated=false;log(text);};
function showFieldErrorsFlow(){for(const {key,message}of fieldIssuesFlow()){const input=document.querySelector(`[data-field="${key}"]`);if(input){input.setAttribute('aria-invalid','true');const id='error-'+key;input.setAttribute('aria-describedby',id);input.insertAdjacentHTML('afterend',`<span class="field-error" id="${id}">${esc(message)}</span>`);}}}
function templateEditorFlow(){modal('Tarifas de la plantilla',`<p class="help">Los cambios se guardan en esta plantilla.</p><div class="template-rate-list">${templateRowsFlow.map((r,i)=>`<fieldset><legend>${esc(r.es)}</legend><div class="grid2"><label class="field">Tarifa USD<input type="number" min="0" step="any" data-template-rate="${i}" value="${esc(r.rate)}"></label><label class="field">Tratamiento IGV<select data-template-tax="${i}">${Object.entries(taxNames).map(([key,name])=>option(key,r.tax,name)).join('')}</select></label></div></fieldset>`).join('')}</div>`,btn('Guardar tarifas','template-save-rates','primary'));}
// Capture at window before legacy handlers so each action has exactly one destination.
window.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;const stop=()=>{e.preventDefault();e.stopImmediatePropagation();};
 if(window.templateModuleAction?.(e,b,a))return;
 if(a==='review')reviewOriginFlow=page;
 if(a==='back-detail'&&page==='review'&&reviewOriginFlow==='templates'){stop();page='templates';mode='proposed';render();return;}
 if(a==='proposed'&&page==='templates'){stop();mode='proposed';render();return;}
 if(a==='actual'&&page==='templates'){stop();mode='actual';render();return;}
 if(a==='templates'){stop();page='templates';render();return;}
 if(a==='template-ref-open'){stop();templateReferencePage='detail';render();return;}
 if(a==='template-ref-back'){stop();templateReferencePage='list';render();return;}
 if(a==='template-ref-search'){stop();templateReferenceFilter=Object.fromEntries([...document.querySelectorAll('[data-ref-filter]')].map(x=>[x.dataset.refFilter,x.value]));render();return;}
 if(a==='template-ref-clear'){stop();templateReferenceFilter={};render();return;}
 if(a==='template-ref-info'){stop();toast('Referencia de solo lectura. Solo se ha inspeccionado el detalle de TPL2609000008.');return;}
 if(a==='template-review-services'){stop();templateEditorFlow();return;}
 if(a==='template-save-rates'){stop();let invalid=false;document.querySelectorAll('[data-template-rate]').forEach(input=>{if(!input.checkValidity()){input.reportValidity();invalid=true;}});if(invalid)return;document.querySelectorAll('[data-template-rate]').forEach(input=>templateRowsFlow[Number(input.dataset.templateRate)].rate=input.value);document.querySelectorAll('[data-template-tax]').forEach(input=>templateRowsFlow[Number(input.dataset.templateTax)].tax=input.value);saveTemplateDraftFlow();$('#modal').close();render();toast('Tarifas de la plantilla guardadas.');return;}
 if(a==='apply-template'&&page==='templates'){stop();const selected=[...document.querySelectorAll('[name="tpl-concept"]:checked:not(:disabled)')];if(!selected.length){toast('Selecciona al menos un servicio para añadir.');return;}const english=['Loaded container loading','Loaded container unloading','Empty container loading','Empty container unloading','Maritime health clearance','Port authority charge'];for(const input of selected){const i=Number(input.value);if(!templateRowsFlow.some(r=>r.es===templateExtrasUI[i]))templateRowsFlow.push({id:Date.now()+i,es:templateExtrasUI[i],en:english[i],group:i<4?'cargo':'authority',rate:'',qty:1,unit:i<4?'Contenedor':'Servicio',tax:'pending',enabled:true,source:'Plantilla',reason:'',provider:'',validated:false});}templateDraftUI.selected.clear();saveTemplateDraftFlow();render();toast('Servicios añadidos a la plantilla.');return;}
 if(a==='save-template'){stop();const name=$('#tpl-name'),scope=$('#tpl-scope');name.setCustomValidity(name.value.trim()?'':'Ingresa un nombre para la plantilla.');if(!name.reportValidity()||!scope.reportValidity())return;if(!templateRowsFlow.length){toast('Añade al menos un servicio a la plantilla.');return;}templateDraftUI.name=name.value.trim();templateDraftUI.scope=scope.value;const version={name:templateDraftUI.name,scope:scope.value,at:new Date().toLocaleString('es-PE'),rows:JSON.parse(JSON.stringify(templateRowsFlow))};versions.push(version);if(!store()){versions.pop();return;}saveTemplateDraftFlow();render();toast('Versión de plantilla guardada.');return;}
 if(a==='approve'){stop();const issues=approvalIssues();if(issues.length){page='detail';tab=fieldIssuesFlow().length?'general':'services';render();showFieldErrorsFlow();modal('Información pendiente',`<p>Completa estos datos para aprobar. Puedes guardar tu avance.</p><ul>${issues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`,btn('Revisar campos','close','primary'));}else modal('Aprobar PDA','<p>Datos y cálculos completos. La aprobación se registrará en este mockup.</p>',btn('Aprobar PDA','confirm-approve','primary'));return;}
 if(a==='confirm-approve'&&approvalIssues().length){stop();toast('Hay información pendiente; revisa nuevamente antes de aprobar.');return;}
},true);
document.addEventListener('input',e=>{if(e.target.id==='tpl-name')e.target.setCustomValidity('');if(e.target.matches('[data-field]')){e.target.removeAttribute('aria-invalid');document.querySelector('#error-'+e.target.dataset.field)?.remove();}});
let templateReferencePage='list',templateReferenceFilter={};
const templateReferenceRecords=[
 ['TPL2609000010','PRUEBA-CAPACITACION Plantilla PDA','Callao','DP World Callao S.R.L.','Buque de carga general/portacontenedores','Liner','Agente Marítimo','Importación/Exportación','Carga General','USD','APROBADA'],
 ['TPL2609000009','LINEA ZIM - PISCO - PARACAS','Pisco','TERMINAL PORTUARIO PARACAS S.A','Buque de carga general/portacontenedores','Liner','Agente Marítimo','Importación/Exportación','Carga General','USD','APROBADA'],
 ['TPL2609000008','LINEA ZIM - CALLAO - DPW','Callao','DP World Callao S.R.L.','Buque de carga general/portacontenedores','Liner','Agente Marítimo','Importación/Exportación','Carga General','USD','APROBADA'],
 ['TPL2608000007','NOMBRE PLANTILLA CAP','Callao','APM Terminals Callao S.A.','Buque de carga general','Liner','Agente Marítimo','Importación','Carga General','USD','APROBADA'],
 ['TPL2608000006','PLANTILLAALONSO','Paita','Terminales Portuarios Euroandinos Paita S.A. (TPE)','Buque de carga general','Tramp','Agente Marítimo','Exportación','Carga Peligrosa IMO','PEN','APROBADA'],
 ['TPL2608000005','TEST -PDA PLANTILLA','Callao','DP World Callao S.R.L.','Buque de carga general','Liner','Agente Marítimo','Importación','Carga General','USD','APROBADA'],
 ['TPL2608000004','BBC VENUS - INMARPACS','Pisco','TERMINAL PORTUARIO PARACAS S.A','Buque de carga general/portacontenedores','Liner','Agente Marítimo','Exportación','Contenerizada','USD','BORRADOR'],
 ['TPL2608000003','prueba','Callao','DP World Callao S.R.L.','Petrolero y derivados','Tramp','Agente Marítimo','Exportación','Carga General','USD','APROBADA'],
 ['TPL2608000002','PDA - PAMPA MELCHORITA','Callao','Valero Peru S.A.C.','Gasero LNG','Tramp','Agente Marítimo','Exportación','Carga Líquida','USD','APROBADA'],
 ['TPL2602000001','Plantilla Buque General Impo','Callao','DP World Callao S.R.L.','Buque de carga general','Liner','Agente General','Importación','Carga General','USD','APROBADA']
];
function templateReferenceFlow(){
 const headers=['Código','Nombre de Plantilla','Puerto','Terminal','Tipo de Nave','Tipo de Servicio','Tipo de Agenciamiento','Tipo de Operación','Tipo de Carga','Moneda','Estado'];
 const filterField=(label,key)=>`<label class="field">${label}${key<2?`<input data-ref-filter="${key}" value="${esc(templateReferenceFilter[key]||'')}">`:`<select data-ref-filter="${key}">${option('',templateReferenceFilter[key]||'',key===10?'BORRADOR, APROBADA':'Elegir '+label.toLowerCase())}${[...new Set(templateReferenceRecords.map(r=>r[key]))].map(v=>option(v,templateReferenceFilter[key]||'')).join('')}</select>`}</label>`;
 const note='<div class="notice actualnote">Referencia de solo lectura observada en el portal el 17/09/2026. Listado de 10 plantillas y detalle de TPL2609000008. Las acciones de mantenimiento no modifican el portal.</div>';
 if(templateReferencePage==='list'){
 const filtered=templateReferenceRecords.filter(r=>Object.entries(templateReferenceFilter).every(([key,value])=>!value||String(r[Number(key)]).toLowerCase().includes(value.toLowerCase())));
 return `<div class="heading"><h1>Consulta Plantilla PDA</h1></div><div class="crumb">Inicio / Plantilla PDA / Consulta Plantilla PDA</div>${note}<section class="card"><div class="bar"><div><h2>Filtros Básicos</h2><small>Ingresa datos para buscar</small></div><span class="spacer"></span>${btn('Nuevo','template-ref-info','primary')}</div><div class="filters">${[0,1,2,3,10].map(i=>filterField(headers[i],i)).join('')}</div><h2>Filtros Avanzados</h2><small>Ingresa datos para buscar</small><div class="filters">${[4,5,6,7,8,9].map(i=>filterField(headers[i],i)).join('')}</div><div class="actions">${btn('Buscar','template-ref-search','primary')}${btn('Limpiar','template-ref-clear')}</div></section><h2 style="margin-top:24px">Resultados (${filtered.length})</h2><div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${filtered.map(r=>`<tr>${r.map((v,i)=>`<td>${i===0?btn(v,r[0]==='TPL2609000008'?'template-ref-open':'template-ref-info','linkbtn'):esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="bar" style="margin-top:16px">${btn('Exportar','template-ref-info')}<span class="spacer"></span><span>Items por página: 10 · 1 de 1</span></div>`;
 }
 const data=templateReferenceRecords[2];
 const fields=[['Nombre de Plantilla PDA*',data[1]],['Puerto*','PECLL - Callao'],...headers.slice(3,9).map((h,i)=>[h+'*',data[i+3]]),['Moneda*','Dólar estadounidense'],['Cliente','ZIM INTEGRATED SHIPPING SERVICE LTD'],['Armador','ZIM INTEGRATED SHIPPING SERVICE LTD'],['Condición de Pago','Sin condición de pago']];
 const portRows=[['USO DE AMARRADERO (I)','LOA/Hora',10,false],['SERVICIOS DE PRACTICAJE-EXPORTACION','Servicio',2,false],['SERVICIO DE LANCHA - PRACTICO A BORDO','Hora',2,true],['OCUPACION DE MUELLES CON PONTONES','Servicio',6,false],...[['DESCARGA CON GRUA PORTICO CONT VACIOS',"Por contenedor (vacío)"],['EMBARQUE CON GRUA PORTICO CONT VACIOS','Por contenedor (vacío)'],['DESCARGA CON GRUA PORTICO CNTR LLENOS','Por contenedor (lleno)'],['EMBARQUE CON GRUA PORTICO CNTR LLENOS','Por contenedor (lleno)']].flatMap(([name,unit])=>[[name+" 20'",unit,100,false],[name.replace('CONT VACIOS','CNTR VACIOS')+" 40'",unit,150,false]]),['LANCHA PARA AUTORIDADES:RECEPCION','Hora',4,true]];
 portRows[5][0]="DESCARGA CON GRUA PORTICO CONT VACIOS 40'";
 const sections=[['Gastos portuarios',portRows],['Gastos por autoridades marítimas',[['AYUDAS A LA NAVEGACION','Por TRG',1,false],['SANIDAD: RECEPCION','Servicio',1,false,'Sol peruano'],['SANIDAD: DESPACHO','Servicio',1,false,'Sol peruano']]],['Comisión de agencia y otros servicios',[['COMISION DE AGENCIA','Servicio',1,true]]]];
 return `${btn('← Volver','template-ref-back')}<div class="heading" style="margin-top:20px"><h1>Ver Plantilla PDA</h1></div><div class="crumb">Inicio / Plantilla PDA / Ver Plantilla PDA</div>${note}<div class="heading"><div><h2>TPL2609000008</h2><div class="statusflow"><span class="badge">BORRADOR</span><span class="badge green">APROBADA</span><span class="badge">INACTIVA</span></div></div><span class="spacer"></span>${['Editar','Inactivar','Eliminar'].map(s=>btn(s,'template-ref-info')).join('')}</div><section class="card"><div class="grid3">${fields.map(([k,v])=>`<label class="field">${k}<input disabled value="${esc(v)}"></label>`).join('')}</div></section><h2 style="margin-top:24px">Categorías y Servicios</h2>${sections.map(([name,list])=>`<details open class="card" style="margin-bottom:14px"><summary style="cursor:pointer;font-weight:600">${name}</summary><div class="tablewrap" style="margin-top:16px"><table><thead><tr>${['Servicio','Unidad de Tarifa','Moneda','Cantidad','A/E','VAT','Comentarios','Acciones'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${list.map(([service,unit,qty,tax,currency])=>`<tr><td>${esc(service)}</td><td>${unit}</td><td>${currency||'Dólar estadounidense'}</td><td>${qty.toFixed(2)}</td><td><input aria-label="A/E ${esc(service)}" type="checkbox" disabled ${tax?'checked':''}></td><td>${tax?'18.00%':''}</td><td></td><td></td></tr>`).join('')}</tbody></table></div></details>`).join('')}<section class="card"><h2>Comentarios</h2><textarea disabled aria-label="Comentarios de plantilla"></textarea></section>`;
}
render();

